# Generated by Django 3.2.4 on 2021-10-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
